#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2024 Dell Inc. or its subsidiaries. All Rights Reserved
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

#############################################
#                WARNING                    #
#############################################
#
# This file is auto generated by the resource
#   module builder playbook.
#
# Do not edit this file manually.
#
# Changes to this file will be over written
#   by the resource module builder.
#
# Changes should be made in the model used to
#   generate this file or in the resource module
#   builder template.
#
#############################################

"""
The module file for sonic_ipv6_neighbors
"""

from __future__ import absolute_import, division, print_function
__metaclass__ = type

DOCUMENTATION = """
---
module: sonic_ipv6_neighbors
version_added: 3.0.0
notes:
- Tested against Enterprise SONiC Distribution by Dell Technologies.
- Supports C(check_mode).
short_description: Manage IPv6 neighbors configuration on SONiC
description:
  - This module provides configuration management of IPv6 neighbors for devices running SONiC
author: Shade Talabi (@stalabi1)
options:
  config:
    description:
      - IPv6 neighbors configuration
    type: dict
    suboptions:
      ipv6_nd_cache_expiry:
        description:
          - Time in seconds until cache expiry, range 60-14400
        type: int
      intf_ipv6_neighbors:
        description:
          - Interface IPv6 neighbors configuration
        type: list
        elements: dict
        suboptions:
          interface:
            description:
              - Interface name 
            type: str
            required: True
          adv_interval_option:
            description:
              - Enable/disable the advertisement interval option
            type: bool
          dad:
            description:
              - Duplicate address detection functionality
              - enable choice enables duplicate address detection on the interface
              - disable choice disables duplicate address detection on the interface
              - disable_ipv6_on_failure choice enables duplicate address detection on the interface and
              - disables IPv6 on the interface when duplicate address detection fails
            type: str
            choices: ['enable', 'disable', 'disable_ipv6_on_failure']
          dnssl:
            description:
              - DNS search list configuration
            type: list
            elements: dict
            suboptions:
              name:
                description:
                  - Domain name suffix
                type: str
                required: True
              valid_lifetime:
                description:
                  - Valid lifetime in seconds, range 0-4294967295
                type: int
          home_agent_config:
            description:
              - Enable/disable home agent configuration
            type: bool
          home_agent_lifetime:
            description:
              - Home agent lifetime in seconds, range 0-65520
            type: int
          home_agent_preference:
            description:
              - Home agent preference value, range 0-65535
              - 0 is the lowest preference 
            type: int
          interval:
            description:
              - Maximum amount of time in seconds between sent route advertisements from the interface
              - Range 1-1800
            type: int
          lifetime:
            description:
              - Lifetime in seconds associated with the default router, range 0-9000
            type: int
          managed_config:
            description:
              - Enable/disable managed address configuration
            type: bool
          min_ra_interval:
            description:
              - Minimum amount of time in seconds between sent route advertisements from the interface
              - Range 1-1350 
            type: int
          min_ra_interval_msec:
            description:
              - Minimum amount of time in milliseconds between sent route advertisements from the interface
              - Range 30-1350000
            type: int
          mtu:
            description:
              - Advertised MTU in bytes, range 0-65535
            type: int
          neighbors:
            description:
              - Neighbors configuration for IPv6 interfaces
            type: list
            elements: dict
            suboptions:
              ip:
                description:
                  - IPv6 address of the neighbor
                type: str
              link_layer_address:
                description:
                  - Link layer address of the neighbor
                type: str
          other_config:
            description:
              - Enable/disable other stateful configuration
            type: bool
          ra_fast_retrans:
            description:
              - Enable/disable fast retransmission of route advertisement packets
            type: bool
          ra_hop_limit:
            description:
              - Maximum number of route advertisement hops, range 0-255
            type: int
            default: 64
          ra_interval_msec:
            description:
              - Maximum amount of time in milliseconds between sent route advertisements from the interface
              - Range 70-1800000
            type: int
          ra_prefixes:
            description:
              - Route advertisement prefixes configuration
            type: list
            elements: dict
            suboptions:
              prefix:
                description:
                  - IPv6 prefix, format X:X::X:X/X
                type: str
                required: True
              no_autoconfig:
                description:
                  - Enable/disable usage of prefix for autoconfiguration
                type: bool
              off_link:
                description:
                  - Enable/disable usage of prefix for on-link determination
                type: bool
              preferred_lifetime:
                description:
                  - Preferred lifetime in seconds, range 0-4294967295
                type: int
              router_address:
                description:
                  - Indicates the router address is a complete IP address
                type: bool
              valid_lifetime:
                description:
                  - Valid lifetime in seconds, range 0-4294967295
                type: int
          ra_retrans_interval:
            description:
              - Amount of time in milliseconds to wait before retransmitting route advertisements from the interface
              - Range 0-4294967295
            type: int
          rdnss:
            description:
              - Recursive DNS server address configuration
            type: list
            elements: dict
            suboptions:
              address:
                description:
                  - IPv6 address, format X:X::X:X
                type: str
                required: True
              valid_lifetime:
                description:
                  - Valid lifetime in seconds, range 0-4294967295
                type: int
          reachable_time:
            description:
              - Duration of time in milliseconds that the neighbor is reachable after receiving a reachability confirmation
              - Range 0-3600000
            type: int
          router_preference:
            description:
              - Default router preference
            type: str
            choices: ['low', 'medium', 'high']
          suppress:
            description:
              - Enable/disable suppression of router advertisement
            type: bool
  state:
    description:
      - The state of the configuration after module completion.
    type: str
    choices:
      - merged
      - deleted
      - overridden
      - replaced
    default: merged
"""
EXAMPLES = """
"""
RETURN = """
before:
  description: The configuration prior to the module invocation.
  returned: always
  type: list
  sample: >
    The configuration returned will always be in the same format
    as the parameters above.
after:
  description: The resulting configuration module invocation.
  returned: when changed
  type: list
  sample: >
    The configuration returned will always be in the same format
    as the parameters above.
after(generated):
  description: The generated configuration module invocation.
  returned: when C(check_mode)
  type: list
  sample: >
    The configuration returned will always be in the same format
     as the parameters above.
commands:
  description: The set of commands pushed to the remote device.
  returned: always
  type: list
  sample: ['command 1', 'command 2', 'command 3']
"""


from ansible.module_utils.basic import AnsibleModule
from ansible_collections.dellemc.enterprise_sonic.plugins.module_utils.network.sonic.argspec.ipv6_neighbors.ipv6_neighbors import Ipv6_neighborsArgs
from ansible_collections.dellemc.enterprise_sonic.plugins.module_utils.network.sonic.config.ipv6_neighbors.ipv6_neighbors import Ipv6_neighbors


def main():
    """
    Main entry point for module execution

    :returns: the result form module invocation
    """
    module = AnsibleModule(argument_spec=Ipv6_neighborsArgs.argument_spec,
                           supports_check_mode=True)

    result = Ipv6_neighbors(module).execute_module()
    module.exit_json(**result)


if __name__ == '__main__':
    main()
